export const CANVAS_W = 400;
export const CANVAS_H = 700;
export const BOTTOM_Y = 620;
export const BALL_SPEED = 12;
export const BLOCK_COLS = 7;
export const BLOCK_W = CANVAS_W / BLOCK_COLS;
export const BLOCK_H = BLOCK_W;
export const PADDLE_SPEED = 420; // 7 px/frame * 60fps
export const PADDLE_WIDTH = 80;
export const PADDLE_Y_OFFSET = 76; // paddle is 76px above startPos.y
export const TOP_BAR_HEIGHT = 50;
export const SPAWN_INTERVAL = 66; // ~4 frames at 60fps in ms
export const HEARTS_MAX = 3;
export const KNIFE_RADIUS = 5;
